### ISSUE TITLE
Compatibility with OpenMP 2.0

### ISSUE THREAD

**Issue by allo-** [exafmm/exafmm#28]
Visual Studio (MSVC) has only OpenMP 2.0, which does not support the ``task`` and ``taskwait`` directives.

As possible workaround seem to be using defines like this

    #if _OPENMP == 200203
    #pragma omp parallel for
                    for(int i = 0; i < Ci->numChilds; i++) {
                            Cell * Cj = Ci->child+i;
                            upwardPass(Cj);
                    }
    #else
                    for(Cell * Cj = Ci->child; Cj!=Ci->child+Ci->numChilds; Cj++) {
    #pragma omp task untied if(Cj->numBodies > 100)
                            upwardPass(Cj);
                    }
    #pragma omp taskwait
    #endif

I did not test it yet, as I am still fixing other issues with MSVC and exafmm.

**Comment by rioyokota** [comment]
There is an easy solution to your problem. Just don't compile with the OpenMP flag. It will ignore all #pramga if you do this. exaFMM is not based on for loops but rather recursive function calls. There is not way for you to have thread parallelism with OpenMP 2.0 anyway.

**Comment by allo-** [comment]
Shouldn't the code be rather equivalent and the difference only in how the pointer is incremented?
I am not an OpenMP expert, I currently just try to get the code running, but my program uses OpenMP so I will need to adapt the source in some way. I have no idea how much performance gain there is from OpenMP in your code, but if it would be possible in some way I would of course like to use it in parallel as well. Sadly I currently need to use MSVC and work around things like very old OpenMP :-/.

**Comment by rioyokota** [comment]
There is a way to formulate FMM with for loops, but FMM has been designed to use a tree traversal based on recursive function calls because it works better with the task based threading model, which scale better than loop parallelization. exaFMM scales perfectly up to 256 threads on a Xeon Phi, depending on the problem size. You can branch your code and delete the all #pragma , but please do not push this back to the repository.
