### ISSUE TITLE
Storing the index of a Body

### ISSUE THREAD

**Issue by allo-** [exafmm/exafmm#31]
I need to track specific bodies.
The build_tree algorithm permutates the bodys by their position in the octree, so I need to store the original index.

Currently I have added a index field to the Body struct, which is assigned to the body in the buffer when ``body.X`` and ``body.q`` are assigned.
This way I can identify bodies afterwards. But there may be more efficient solutions, like adding an ``indexes`` and an ``indexes_buffer``.

What kind of implementation would you prefer?

**Comment by rioyokota** [comment]
This can be done by adding an index I to the Body struct. I currently don't have it to minimize of overhead of loading the Body strucut, but it is just one line to change. You can also define a comparison operator for the Body struct so that you can pass bodies to std::sort and it will sort them according to the index without yiu even writing a sorting algorithm.

**Comment by allo-** [comment]
Here a small implementation, compatible with ``std::sort``.
https://github.com/allo-/exafmm/tree/indexed_bodies
